# Generated by Django 2.2.2 on 2020-06-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topfoods',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
