# Generated by Django 2.2.2 on 2020-06-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_topfoods_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('cimg', models.ImageField(upload_to='foodpic')),
                ('cdesc', models.TextField()),
            ],
        ),
    ]
